modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="f"
version="1.0.0"
displayName="f"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Hello, MCreator"

[[dependencies.f]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




